#!/bin/sh
LINES=10
freqs="$(cpupower frequency-info | grep 'available cpufreq' \
  | sed 's/.*://' \
  | sed 's/, \| /\n/g' \
  | sed 's/^ *//' \
  | uniq)"
freq=$(echo "$freqs" | dmenu -l "$LINES" -p "Freq: ")
