#!/bin/sh

# set an alias with alias drc="sudo dopenrc-runlevel"

run_folder=/etc/runlevels
runlevel="$(find "$run_folder" -mindepth 1 -maxdepth 1 -type d  | sed 's:.*/::' | sort -h | dmenu -p "Runlevel: ")"
[ -n "$runlevel" ] && openrc "$runlevel"
