#!/bin/sh

#don't forget to set $USERTAGS and $BOOKMARKS to whatever path

DMENULINES=15

help () {
    echo "Call without an argument to be prompted with dmenu."
    echo "Flags:"
    printf "-h, --help\n-a, --add\n-e, --edit\n"
}

add () {
    url="$(xclip -o | dmenu -p 'RSS url: ')"
    desc="$(dmenu -p 'description: ')"

    [ ! -e "$url" ] && printf "%s \"%s\"\\n" "$url" "$desc" >>"$NEWBOAT_RSS_URLS"
}

edit () {
    echo "Not implemented. Edit \$NEWSBOAT_RSS_URLS yourself at $NEWSBOAT_RSS_URLS." && exit 1
}

promptflag () {

    action="$(printf 'add\nedit (not implemented)\n' | dmenu -l 4 -p 'action:')"
    [ "$action" = "edit" ]  && edit
    [ "$action" = "add" ]   && add
}

[ "$1" = '-h' ] || [ "$1" = '--help' ] && help
[ "$1" = '-a' ] || [ "$1" = '--add' ]  && add
[ "$1" = '-e' ] || [ "$1" = '--edit' ] && edit
[ -z "$1" ] && promptflag
[ -n "$2" ] && echo "Too many arguments: use one or none." && exit 1
